import rawMeta from "@/data/catalogue_meta.json";
import rawProducts from "@/data/products.json";

/** Courses in the Rock Paper Scissors Date Night mission. */
export type Course = "starter" | "main" | "side" | "dessert" | "drink" | "wildcard";

export const MISSION_COURSES: Course[] = ["starter", "main", "side", "dessert", "drink", "wildcard"];

/** Behavioural attributes, each 0–1. Matched against persona traits in scoring. */
export interface ProductAttributes {
  premium: number;
  indulgent: number;
  healthy: number;
  adventurous: number;
  romantic: number;
  shareable: number;
  viralPotential: number;
  familiar: number;
}

/** One M&S product, generated by scripts/build_catalogue.py — do not edit the JSON by hand. */
export interface CatalogueProduct {
  id: string;
  name: string;
  course: Course;
  /** Shelf price in £ at the store named in `catalogueMeta.priceStore`. */
  price: number;
  /** "each", or "catch_weight_displayed_pack" for weighed items priced per displayed pack. */
  priceBasis: string;
  brand: string | null;
  weight: string | null;
  description: string | null;
  dietary: string[];
  isNew: boolean;
  image: string;
  url: string;
  attributes: ProductAttributes;
  /** 0–1 from how often couples bought it in the TikTok sample; 0 if never seen. */
  trendSignal: number;
  /** Times the product was seen bought across the TikTok posts. */
  observedMentions: number;
  /** IDs of the posts it appeared in (v01…v16 videos, c01…c06 carousels). */
  observedPosts: string[];
}

export interface CatalogueMeta {
  priceStore: { id: string; name: string; address: string; url: string };
  pricesCapturedAt: string;
  rawProducts: number;
  catalogueProducts: number;
  perCourse: Record<Course, number>;
  tiktokProductsSpotted: number;
  tiktokProductsInCatalogue: number;
}

export const catalogue = rawProducts as CatalogueProduct[];

export const catalogueMeta = rawMeta as CatalogueMeta;

const byId = new Map(catalogue.map((product) => [product.id, product]));

export function getProduct(id: string): CatalogueProduct | undefined {
  return byId.get(id);
}

export function productsForCourse(course: Course): CatalogueProduct[] {
  return catalogue.filter((product) => product.course === course);
}
